[general]
import = ["~/.config/alacritty/catppuccin-latte.toml"]

[window]
# decorations_theme_variant = "Light"

[font]
# size = 11

[bell]
animation = "Ease"
duration = 500
color = "#df8e1d"

[terminal.shell]
program = "/bin/tmux"
args = ["new-session"]
