---@meta vim.lsp

-- vim.lsp._capability = require('vim.lsp._capability')
-- vim.lsp._changetracking = require('vim.lsp._changetracking')
-- vim.lsp._folding_range = require('vim.lsp._folding_range')
-- vim.lsp._snippet_grammar = require('vim.lsp._snippet_grammar')
-- vim.lsp._tagfunc = require('vim.lsp._tagfunc')
-- vim.lsp._watchfiles = require('vim.lsp._watchfiles')

vim.lsp.buf = require('vim.lsp.buf')
vim.lsp.client = require('vim.lsp.client')
vim.lsp.codelens = require('vim.lsp.codelens')
vim.lsp.completion = require('vim.lsp.completion')
vim.lsp.diagnostic = require('vim.lsp.diagnostic')
vim.lsp.document_color = require('vim.lsp.document_color')
vim.lsp.handlers = require('vim.lsp.handlers')
vim.lsp.inlay_hint = require('vim.lsp.inlay_hint')
vim.lsp.inline_completion = require('vim.lsp.inline_completion')
vim.lsp.linked_editing_range = require('vim.lsp.linked_editing_range')
vim.lsp.log = require('vim.lsp.log')
vim.lsp.on_type_formatting = require('vim.lsp.on_type_formatting')
vim.lsp.protocol = require('vim.lsp.protocol')
vim.lsp.rpc = require('vim.lsp.rpc')
vim.lsp.semantic_tokens = require('vim.lsp.semantic_tokens')
vim.lsp.util = require('vim.lsp.util')

-- vim.treesitter._fold = require('vim.treesitter._fold')
-- vim.treesitter._query_linter = require('vim.treesitter._query_linter')
-- vim.treesitter._range = require('vim.treesitter._range')

vim.treesitter.dev = require('vim.treesitter.dev')
vim.treesitter.highlighter = require('vim.treesitter.highlighter')
vim.treesitter.language = require('vim.treesitter.language')
vim.treesitter.languagetree = require('vim.treesitter.languagetree')
vim.treesitter.query = require('vim.treesitter.query')
